on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: sillyangel/releases-to-discord@v1.0.0
        with:
          webhook_url: ${{ secrets.https://discord.com/api/webhooks/1269150937436520518/XS6mw2onlcUaFCOLAq-vaUrahIdvj69XhJYPm9V7FxY9GJY5N0BnBFS1zUO5kYBe4qWU }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
